### PR TITLE
Enable Long press Power-off

### PR DESCRIPTION
**Pull request by Rjasuja**
Changes powerbtn.sh to shutdown once the power button is pressed
Fix aero-led-ctrl script
Issue : #10

### CODE REVIEW

**Comment by Rjasuja** [comment]
Previous PR: #13 requires X11 display session to be started. With this PR, long press Power-off hold good even without logging in once.

**Review by avinash-palleti — APPROVED** [review]

**Comment by anselmolsm** [comment]
Calling `shutdown -h now` will certainly power the board off, but does it perform a smooth shutdown like the Yocto-based system does?

**Comment by avinash-palleti** [comment]
Calling `shutdown -h now` itself means soft shutdown. 
`/etc/acpi/powerbtn.sh` script which is getting modified as part of this PR, earlier also it was calling `shutdown -h now` in addition to this it was closing x-sessions which had dependency on x11. 
So removed those x11 related commands and placed only `shutdown` command.

**Comment by anselmolsm** [comment]
[/etc/acpi/powerbtn.sh is overwritten](https://github.com/intel-aero/packages/pull/17/files#diff-085c80f5ecab7c79992baa012bb089feR3) to only execute `shutdown -h now`. It does shutdown the system, but we can't say it performs the same steps as the Yocto-based system does, like the LED sequence, which might be considered minor, but it has been documented as a visual feedback for the shutdown process.

**Comment by avinash-palleti** [comment]
Please check the existing script at http://pastebin.intel.com/hifovuduxo.bash
All the checks that it is doing currently are related to Xserver, which is not active in our case. 
LED sequence is not handled by this script.

**Comment by anselmolsm** [comment]
> LED sequence is not handled by this script.

That's the point: Is anything going to handle that?

**Comment by avinash-palleti** [comment]
https://github.com/intel-aero/meta-intel-aero-base/blob/master/recipes-support/notify-led/files/shutdown-led-notify.service

This service files handles that, whenever shutdown is initiated and this service is killed, it will take care of LED sequence. For now this systemd service files are not part of Aero Ubuntu. We can add these.

**Comment by anselmolsm** [comment]
>  For now this systemd service files are not part of Aero Ubuntu. We can add these.

Please do that.

**Review by anselmolsm — CHANGES_REQUESTED** [review]
See comments.

**Comment by avinash-palleti** [comment]
This PR is independent of LED sequence issue we can have this checked in. I will rebase and commit.

**Comment by anselmolsm** [comment]
You can submit separately, as long as you complete the task completely.

**Comment by avinash-palleti** [comment]
LED service files are already part of aero-systemd package.
Closing this PR as separate PRs submitted for both the issues. (sleep command and power button)
https://github.com/intel-aero/packages/pull/22
https://github.com/intel-aero/packages/pull/21

**Pull request closed without merging**
